name: release

on:
  push:
    tags:
      - 'fontless@*'
      - 'fontaine@*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - run: corepack enable
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ“¦ Install dependencies
        run: pnpm install

      - name: ðŸ›  Build project
        run: pnpm build

      - name: ðŸ“¦ Release fontaine
        if: startsWith(github.ref, 'refs/tags/fontaine@')
        run: pnpm publish --no-git-checks
        working-directory: packages/fontaine

      - name: ðŸ“¦ Release fontless
        if: startsWith(github.ref, 'refs/tags/fontless@')
        run: pnpm publish --no-git-checks
        working-directory: packages/fontless

      - run: pnpm changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
